#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"

// Program for testing gyroscope integration accuracy

task main()
{
	HTGYROstartCal(gyro);

	float TARGET = 360;
	float sum = 0;
	int timestep = 10;
	while (abs(sum) <= TARGET)
	{
		float current = HTGYROreadRot(gyro);
		current /= (1000.00 / (float)timestep);
		sum += current;
		wait1Msec(10);
	}
	PlayTone(300, 30);
	wait10Msec(30);

	while (true) {}
}
