#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S2,     col_side,       sensorCOLORFULL)
#pragma config(Sensor, S3,     col_front,      sensorCOLORFULL)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     frontR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontL,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     backR,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backL,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    hookbR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    hookbL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    hookfR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hookfL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    autoarm,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

// Program for testing gyroscope during an actual turn

void drive(int l, int r)
{
	motor[frontL] = l;
	motor[backL] = l;
	motor[frontR] = r;
	motor[backR] = r;
}

task main()
{
	servo[hookfR] = 60;
	servo[hookfL] = 205;
	servo[hookbR] = 210;
	servo[hookbL] = 40;
	wait1Msec(600);

	HTGYROstartCal(gyro);

	int interval = 10;
	float targetRotation = 65;
	float sum = 0;
	drive(-70, 70);
	while (abs(sum) <= targetRotation)
	{
		float current = HTGYROreadRot(gyro);
		current /= (1000.00 / (float)interval);
		sum += current;
		wait1Msec(10);
	}
	drive(0, 0);
	PlayTone(300, 40);
	wait10Msec(40);
}
