#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     liftL,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     liftR,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_1,     boxlift1,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     boxlift2,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    autonomous,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    box1,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    box2,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

// Macro functions to replace common calls
void stopMoving();
void setMotors(int l, int r);

// Function to raise the lift
void raiseLift();
// Function to deposit block
void depositBlock();
// Function to move to ramp from end position
void moveToRamp();

bool tooFar = false;
bool irDetected = false;
bool blockDeposited = false;

// Parallel task to check distance from start position
task checkDist()
{
    // Loop that keeps track of time while going forward
	for(int x = 0; x < 2250; x++)
	{
		// Waits 1 Millisec 2250 times, or 2.25 seconds
		wait1Msec(1);
		// If the ir is detected, we're at the last block, and
		// the block hasn't been detected already
		if((irDetected || x == 2250) && !blockDeposited)
		{
			// Offset for difference between 1-2 and 3-4
			if(x < 900)
			{
				setMotors(75,75);
				wait1Msec(500);
				depositBlock();
				setMotors(75,75);
				x += 500;
			}
			else
			{
				setMotors(75,75);
				wait1Msec(800);
				depositBlock();
				setMotors(75,75);
				x += 800;
			}
		}
	}
	tooFar = true;
}

task main()
{
	// Initialization
	wait1Msec(200);
	servo[flap] = 0;
	wait1Msec(100);
	servoChangeRate[autonomous] = 1;
	servo[autonomous] = 240;
	servo[box1] = 255;
	servo[box2] = 0;
	wait1Msec(200);
	//waitForStart(); // Wait for the beginning of autonomous period

	// Raise the lift and block lift off ground
	raiseLift();

	// Move forward, slight delay to get closer to baskets
	setMotors(75,75);
	wait1Msec(400);

	// Start task to check distance past baskets
	StartTask(checkDist);
	// Loop to check if ir is detected
	// Boolean tooFar switches when checkDist finishes
	while(!tooFar)
	{
  		if(SensorValue[IRSensor] == 5)
  			irDetected = true;
	}
	// Move to the ramp from the static end pos
	moveToRamp();
	// Stop moving
	stopMoving();
}

void moveToRamp()
{
	setMotors(50,-50);
	wait1Msec(500);
	setMotors(50,50);
	wait1Msec(1600);
	setMotors(50,-50);
	wait1Msec(300);
	setMotors(50,50);
	wait1Msec(1400);
	setMotors(50,-50);
	wait1Msec(900);
	/*setMotors(100,100);
	wait1Msec(2400);*/
}

void depositBlock()
{
	stopMoving();
	servoChangeRate[autonomous] = 10;
	servo[autonomous] = 20;
	wait1Msec(500);
	servo[autonomous] = 240;
	wait1Msec(800);
	setMotors(75,75);
	blockDeposited = true;
}

void raiseLift()
{
	motor[liftL] = 100;
	motor[liftR] = 100;
	motor[boxlift2] = 25;
	wait1Msec(500);
	motor[boxlift2] = 0;
	motor[liftL] = 0;
	motor[liftR] = 0;
}

void stopMoving()
{
	motor[motorL] = 0;
	motor[motorR] = 0;
}

void setMotors(int l, int r)
{
	motor[motorL] = l;
	motor[motorR] = r;
}
